name: 'Cache poetry and venv'
description: 'Cache poetry and venv'
inputs:
  poetry-version:
    description: "Version of poetry, used for cache hash. If you change this, automatically invalidates the cache."
    required: true
    default: '0.0.0'
  cache-version:
    description: "Cache version, used for cache key. If you change this, automatically invalidates the cache."
    required: true
    default: '0.0.0'
  python-version:
    description: "Python version, used for cache key. If you change this, automatically invalidates the cache."
    required: true
    default: '0.0.0'
outputs:
  venv-cache-hit:
    description: "Whether there was a cache hit on .venv"
    value: ${{ steps.cached-poetry-dependencies.outputs.cache-hit }}
  poetry-cache-hit:
    description: "Whether there was a cache hit on the poetry installation"
    value: (${{ steps.cached-poetry-unix.outputs.cache-hit }} || ${{ steps.cached-poetry-windows.outputs.cache-hit }}) 


runs:
  using: "composite"
  steps:
    # Override version numbers to avoid invalidating cache on version bump
    - name: Override version number from pyproject.toml
      shell: bash
      run: |
        echo "🚧 Overriding version number from pyproject.toml so the project's version doesn't invalidate cache "
      
    - name: Linux, Overwrite version number from pyproject.toml, so it doesn't invalidate cache.
      id: remove-version-from-toml-macos
      if: (runner.os == 'ubuntu-latest' || runner.os == 'windows-latest')
      shell: bash
      run: |
        ls
        sed -i "s/version = \".*\"/version = \"0.0.0\"/g" pyproject.toml
        cat pyproject.toml

    - name: Mac, Overwrite version number from pyproject.toml, so it doesn't invalidate cache.
      id: remove-version-from-toml-ubuntu
      if: runner.os == 'macos-latest'
      shell: bash
      run: |
        sed -i '' "s/version = \".*\"/version = \"0.0.0\"/g" pyproject.toml
        cat pyproject.toml

    - name: Load cached venv
      shell: bash
      run: |
        echo "🚧 Loading cached venv"

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2.1.6
      with:
        path: |
          .venv
        # Cache the complete venv dir for a given os, python version, pyproject.toml
        key: ${{ runner.os }}-python-${{ inputs.python-version }}-poetry-${{ inputs.poetry-version }}-toml-${{ hashFiles('pyproject.toml') }}-cache-${{ inputs.cache-version }}

    - name: Load cached poetry install
      shell: bash
      run: |
        echo "🚧 Loading cached poetry install"

    - name: Mac, Linux, Load cached .local (Poetry install location)
      id: cached-poetry-unix
      if: (runner.os == 'ubuntu-latest' || runner.os == 'macos-latest')
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.local/
        # Cache the complete venv dir for a given os, python version, pyproject.toml
        key: ${{ runner.os }}-python-${{ inputs.python-version }}-poetry-${{ inputs.poetry-version }}-toml-${{ hashFiles('pyproject.toml') }}-cache-${{ inputs.cache-version }}

    - name: Windows, Load cached Poetry install (Poetry install location)
      id: cached-poetry-windows
      if: runner.os == 'windows-latest'
      uses: actions/cache@v2.1.6
      with:
        path: |
          %APPDATA%\pypoetry
        # Cache the complete venv dir for a given os, python version, pyproject.toml
        key: ${{ runner.os }}-python-${{ inputs.python-version }}-poetry-${{ inputs.poetry-version }}-toml-${{ hashFiles('pyproject.toml') }}-cache-${{ inputs.cache-version }}
    
    - name: Load cached venv
      shell: bash
      run: |
        echo "✅ Finished cache processing"
