name: CI Pytest
on:
  push:
    branches: [ master ]

jobs:
  cache-poetry-and-venv:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        
    steps:
    - name: Cache poetry and venv
      id: cache-poetry-and-venv
      uses: MartinBernstorff/cache-poetry-and-venv@v0.3.0