name: CI Pytest
on:
  push:
    branches: [ master ]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.9]
        
    steps:
    ### Setup prerequisites
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Checkout repo
      uses: actions/checkout@v3

    ### Caching
    - name: Cache poetry and venv
      uses: MartinBernstorff/cache-poetry-and-venv@v0.1.0
