name: Test action
on:
  push:
    branches: [ master ]

jobs:
  cache-poetry-and-venv:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Cache poetry and venv
      id: cache-poetry-and-venv
      uses: ./action.yml 